import fs from "fs/promises";
import path from "path";
import { log, isSafePackageRef } from "./utils.js";
import { generateSkillFingerprint } from "./fingerprint.js";
import { lintSkillArtifact, lintSkillSet, lintAgentArtifact } from "./lint.js";

export const STATE_FILE = "SKILLS_MINED.json";

// Escape a value for a markdown table cell
function cell(value) {
  return String(value == null ? "" : value).replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim() || "n/a";
}

/**
 * Render SKILLS_MINED.md deterministically from structured run data.
 * No LLM: the data is already structured — model-rendering the report was a
 * fidelity risk (mangled tables, dropped rows), not a capability.
 */
export function renderReport(data) {
  const lines = [];
  const push = (...xs) => lines.push(...xs);

  const built = data.skills.filter(s => s.origin === "BUILD" || s.origin === "BUILT");
  const extended = data.skills.filter(s => s.origin === "EXTEND" || s.origin === "EXTENDED");
  // REUSE candidates are never authored (that's the point), so they exist only
  // in the candidate ledger — derive the reused list from there, or the report
  // structurally under-counts the dedupe outcome it exists to record.
  const reused = data.candidates.filter(
    c => c.type !== "agent" && (c.decision === "REUSE" || c.decision === "REUSED")
  );
  const rejected = data.candidates.filter(c => c.decision === "REJECT");
  const deferred = data.candidates.filter(c => c.decision === "DEFER");

  push(`# Skills Mined — \`${data.repoName}\``);
  push("");
  push(`> Generated by the **skill-mining** skill on \`${data.date}\`. Scope: \`${data.scope}\`.${data.headCommit ? ` HEAD: \`${data.headCommit}\`.` : ""}`);
  push("");
  push("## Summary");
  push("");
  push(`- Candidates considered: **${data.candidates.length}**`);
  push(`- Built: **${built.length}** · Reused: **${reused.length}** · Extended: **${extended.length}** · Rejected: **${rejected.length}** · Deferred: **${deferred.length}**`);
  push(`- Agents composed: **${data.agents.length}**${data.exclusions.length ? ` (${data.exclusions.join("; ")})` : ""}`);
  push("");

  // Coverage — what the pass actually looked at, so bounded ≠ silently exhaustive
  if (data.coverage) {
    push("## Coverage (what this pass surveyed)");
    push("");
    push(`- Files surveyed: **${data.coverage.filesCount}**; source files sampled for convention detection: **${data.coverage.samplesCount}**`);
    if (data.coverage.painTotal != null) {
      push(`- Pain markers (TODO/FIXME/HACK) found: **${data.coverage.painTotal}**`);
    }
    for (const cap of data.coverage.caps || []) {
      push(`- Bound: ${cap}`);
    }
    push("");
  }

  push("## Candidate ledger");
  push("");
  push("Every candidate considered, with score and decision. Nothing dropped silently.");
  push("Scores shown are *post–Gate A* (the independent skeptic's blind re-score; Δ is");
  push("the proposer-vs-skeptic disagreement — high Δ is signal).");
  push("");
  push("| Candidate | Type | Freq | Lev | Bsp | Stab | Ver | Δ | Evidence | Decision | Gate A objection / Source |");
  push("|---|---|:--:|:--:|:--:|:--:|:--:|:--:|---|---|---|");
  for (const c of data.candidates) {
    const s = c.scores || {};
    push(`| ${cell(c.name)} | ${cell(c.type)} | ${s.freq ?? "-"} | ${s.lev ?? "-"} | ${s.bsp ?? "-"} | ${s.stab ?? "-"} | ${s.ver ?? "-"} | ${c.gateADelta ?? "-"} | ${c.evidenceVerified === false ? "⚠ unverified" : "✓"} | **${cell(c.decision)}** | ${cell(c.objection || c.source)} |`);
  }
  push("");

  push("## Built / reused skills — with identity");
  push("");
  push("| Skill | Origin | Path | Source / version pin | Content fingerprint (whole dir) | Verification |");
  push("|---|---|---|---|---|---|");
  for (const s of data.skills) {
    push(`| \`${cell(s.name)}\` | ${cell(s.origin)} | \`${cell(s.path)}\` | ${cell(s.source)} | \`${cell(s.fingerprint)}\` | ${cell(s.verification)} |`);
  }
  push("");

  const reuseChecked = data.skills.filter(s => s.reuseCheckStatus && s.reuseCheckStatus !== "n/a");
  if (reuseChecked.length > 0) {
    push("**Reuse-check status (required for BUILT/EXTENDED rows):**");
    push("");
    for (const s of reuseChecked) {
      push(`- \`${s.reuseCheckStatus}\``);
    }
    push("");
  }

  push("Per-skill **file manifest** (the recorded file list partial modes compare against;");
  push("the whole-directory fingerprint is the hash of this manifest):");
  push("");
  for (const s of data.skills) {
    if (!s.manifestText) continue;
    push("```");
    push(s.manifestText);
    push("```");
    push("");
  }

  push("## Composed agents");
  push("");
  if (data.exclusions.some(e => e.includes("--no-agents"))) {
    push("*Section omitted: agents skipped by user choice (`--no-agents`).*");
  } else if (data.agents.length === 0) {
    push("*No agent roles survived composition and the cold-load gate.*");
  } else {
    for (const a of data.agents) {
      push(`- **\`${a.name}\`** — loads ${a.loadedSkills.map(s => `\`${s}\``).join(", ") || "(skills selected in definition)"}. ${a.verification || ""}`);
    }
  }
  push("");

  push("## Team manifest");
  push("");
  if (data.exclusions.some(e => e.includes("--no-team") || e.includes("--no-agents"))) {
    push("*Section omitted: team manifest skipped by user choice.*");
  } else if (!data.teamManifest) {
    push("*No team manifest (no agents composed).*");
  } else {
    push(data.teamManifest);
  }
  push("");

  push("## Reused / Extended");
  push("");
  if (reused.length + extended.length === 0) {
    push("*None.*");
  } else {
    // Defense at the sink: `source` becomes a copy-paste shell command. Even
    // though the full run validates it upstream, the legacy partial-mode path
    // (LLM-parsed from old markdown) reaches here too — never interpolate an
    // unvalidated package ref into an `npx skills add` line.
    for (const c of reused) {
      if (isSafePackageRef(c.source)) {
        push(`- **\`${c.name}\`** ← install \`npx skills add ${c.source}\` — ${cell(c.justification || c.objection || "covered by community skill")}`);
      } else {
        push(`- **\`${c.name}\`** ← source \`${cell(c.source || "(not recorded)")}\` failed package-reference validation; do not run it as-is — ${cell(c.justification || "verify manually")}`);
      }
    }
    for (const s of extended) {
      const ref = isSafePackageRef(s.source) ? `\`${s.source}\`` : `${cell(s.source)} (unvalidated — verify before installing)`;
      push(`- **\`${s.name}\`** (extended) ← ${ref}`);
    }
  }
  push("");

  push("## Deferred — next mining pass");
  push("");
  if (deferred.length === 0) {
    push("*None.*");
  } else {
    for (const c of deferred) {
      push(`- **\`${c.name}\`** — ${cell(c.objection || "deferred")}. Revisit when: ${cell(c.revisitWhen || "next mining pass")}.`);
    }
  }
  push("");

  if (rejected.length > 0) {
    push("## Rejected — do not re-mine without new evidence");
    push("");
    for (const c of rejected) {
      push(`- **\`${c.name}\`** — ${cell(c.objection || c.justification || "rejected during scoring/challenge")}`);
    }
    push("");
  }

  push("## How to install");
  push("");
  push("```bash");
  push("# From this repo:");
  push(`npx skills add ${data.installHint || "<user>/<repo>"}`);
  push("# or copy into your harness skills dir (see references/cross-harness.md)");
  push("```");
  push("");

  return lines.join("\n");
}

/**
 * Phase 7 — deterministic finalize: lint artifacts (fail closed), write skill
 * and agent files, compute fingerprints, and emit SKILLS_MINED.md plus the
 * SKILLS_MINED.json sidecar that partial modes read instead of LLM-parsing
 * their own report.
 */
export async function runReportPhase(targetDir, finalCandidates, verifiedSkills, composedAgentsResult, survey, args, extras = {}) {
  log.phase("7", "Verify & Report (deterministic)");

  const absoluteTarget = path.resolve(targetDir);

  // Lint before writing anything — fail closed on structural defects
  log.step("Linting artifacts (frontmatter, names, verification sections, dangling refs)...");
  const setErrors = lintSkillSet(verifiedSkills);
  const lintFailures = [];
  for (const skill of verifiedSkills) {
    // Authoring standards apply to what we authored; REUSED community skills
    // are verified by version pin + fingerprint, not by our lint rules.
    const origin = (skill.decision || "").toUpperCase();
    if (origin === "REUSE" || origin === "REUSED") continue;
    const errors = (skill.lintErrors && skill.lintErrors.length > 0)
      ? skill.lintErrors
      : lintSkillArtifact({ name: skill.name, markdown: skill.rawMarkdown });
    if (errors.length > 0) {
      lintFailures.push(`${skill.name}: ${errors.join("; ")}`);
    }
  }
  // Agent lint never aborts the report — a cosmetic frontmatter defect in one
  // composed agent must not discard every verified skill. Offending agents are
  // dropped (and surfaced); skill lint stays fail-closed below.
  let agentsToWrite = composedAgentsResult ? composedAgentsResult.agents : [];
  if (composedAgentsResult) {
    const dropped = [];
    agentsToWrite = composedAgentsResult.agents.filter(agent => {
      // Agents re-loaded from prior state (--report-only) carry no markdown —
      // their files already exist on disk and were linted when authored.
      if (!agent.rawMarkdown) return true;
      const errors = lintAgentArtifact({ name: agent.name, markdown: agent.rawMarkdown });
      if (errors.length > 0) {
        dropped.push(`${agent.name}: ${errors.join("; ")}`);
        return false;
      }
      return true;
    });
    for (const d of dropped) {
      log.warn(`Agent dropped at report lint (skills are unaffected): ${d}`);
    }
  }
  if (setErrors.length > 0 || lintFailures.length > 0) {
    // Full runs fail closed: we authored these artifacts this pass and must not
    // ship them broken. Partial modes re-emit artifacts authored by possibly
    // older versions whose rules differed — there, lint findings are warnings,
    // not a reason to brick a previously valid report (extras.lintMode="warn").
    if (extras.lintMode === "warn") {
      log.warn("Artifact lint found issues in pre-existing skills (non-fatal in partial mode):");
      for (const e of [...setErrors, ...lintFailures]) log.substep(e);
    } else {
      throw new Error(
        `Artifact lint failed (fail closed — nothing written):\n` +
        [...setErrors, ...lintFailures].map(e => `  - ${e}`).join("\n")
      );
    }
  } else {
    log.step("All artifacts lint clean");
  }

  // Surface stale skill directories from prior runs. A skill that was BUILD
  // last pass and REJECT/DEFER this pass leaves its directory behind — and a
  // harness scanning .agents/skills/ will keep loading it while the report
  // claims it's gone. Deleting user files unprompted is worse than warning,
  // so reconcile loudly and record it in the report's coverage bounds.
  const staleDirs = [];
  try {
    const skillsRoot = path.join(absoluteTarget, ".agents", "skills");
    const existing = await fs.readdir(skillsRoot, { withFileTypes: true });
    const currentNames = new Set(verifiedSkills.map(s => s.name));
    for (const entry of existing) {
      if (entry.isDirectory() && !currentNames.has(entry.name)) {
        staleDirs.push(entry.name);
      }
    }
    if (staleDirs.length > 0) {
      log.warn(`Stale skill directories from prior runs (not in this run's verified set — harnesses will still load them): ${staleDirs.join(", ")}`);
      log.warn(`Remove them manually if they were rejected on purpose: rm -r .agents/skills/{${staleDirs.join(",")}}`);
    }
  } catch (err) {
    // .agents/skills does not exist yet — nothing stale
  }

  // Write skill files and compute fingerprints
  log.step("Writing skill files and computing directory fingerprints...");
  const skillDetails = [];
  for (const skill of verifiedSkills) {
    const skillDir = path.join(absoluteTarget, ".agents", "skills", skill.name);
    await fs.mkdir(skillDir, { recursive: true });
    await fs.writeFile(path.join(skillDir, "SKILL.md"), skill.rawMarkdown, "utf8");
    log.substep(`Wrote SKILL.md to .agents/skills/${skill.name}/`);

    const fpResult = await generateSkillFingerprint(skillDir, skill.name);
    skillDetails.push({
      name: skill.name,
      origin: skill.decision,
      source: skill.source,
      path: `.agents/skills/${skill.name}/`,
      fingerprint: fpResult.fingerprint,
      manifestText: fpResult.manifestText,
      verification: skill.verification,
      reuseCheckStatus: skill.reuseCheckStatus,
    });
  }

  // Write agent files
  const agents = [];
  if (!args.noAgents && composedAgentsResult) {
    log.step("Writing agent files...");
    const agentsDir = path.join(absoluteTarget, ".agents", "agents");
    await fs.mkdir(agentsDir, { recursive: true });
    for (const agent of agentsToWrite) {
      const agentPath = path.join(agentsDir, `${agent.name}.md`);
      if (agent.rawMarkdown) {
        await fs.writeFile(agentPath, agent.rawMarkdown, "utf8");
        log.substep(`Wrote agent definition to .agents/agents/${agent.name}.md`);
      } else {
        // State-loaded agent (--report-only): never advertise a persona whose
        // backing file was deleted/renamed since the prior run — stat first.
        try {
          await fs.access(agentPath);
        } catch (err) {
          log.warn(`Agent "${agent.name}" recorded in prior state but .agents/agents/${agent.name}.md is missing — dropped from the report.`);
          continue;
        }
        log.substep(`Agent "${agent.name}" carried from prior state (file present on disk)`);
      }
      agents.push({
        name: agent.name,
        loadedSkills: agent.loadedSkills || [],
        verification: agent.verification || "",
      });
    }
  }

  const exclusions = [];
  if (args.noAgents) exclusions.push("agents skipped (--no-agents)");
  else if (args.noTeam) exclusions.push("team manifest skipped (--no-team)");

  const data = {
    repoName: path.basename(absoluteTarget),
    scope: targetDir,
    date: new Date().toISOString().split("T")[0],
    headCommit: survey?.git?.headCommit || null,
    exclusions,
    coverage: {
      filesCount: survey?.filesCount ?? 0,
      samplesCount: Object.keys(survey?.sourceSamples || {}).length,
      painTotal: survey?.painMarkers?.available ? survey.painMarkers.total : null,
      caps: [
        ...(extras.caps || []),
        ...(staleDirs.length > 0
          ? [`stale skill directories on disk, not produced by this run (review/remove manually): ${staleDirs.join(", ")}`]
          : []),
      ],
    },
    candidates: finalCandidates.map(c => ({
      name: c.name,
      type: c.type,
      scores: c.scores || null,
      decision: c.decision,
      objection: c.objection || null,
      justification: c.justification || null,
      source: c.source || null,
      evidenceVerified: c.evidenceVerified !== false,
      evidenceNotes: c.evidenceNotes || null,
      gateADelta: c.gateADelta ?? null,
      revisitWhen: c.revisitWhen || null,
    })),
    skills: skillDetails,
    agents,
    teamManifest: composedAgentsResult?.teamManifest || null,
    installHint: extras.installHint || null,
  };

  log.step("Rendering SKILLS_MINED.md (deterministic — no LLM)...");
  const markdown = renderReport(data);
  await fs.writeFile(path.join(absoluteTarget, "SKILLS_MINED.md"), markdown, "utf8");
  await fs.writeFile(path.join(absoluteTarget, STATE_FILE), JSON.stringify(data, null, 2) + "\n", "utf8");
  log.success(`Wrote mining report to: SKILLS_MINED.md (+ machine-readable ${STATE_FILE})`);

  return data;
}

/**
 * Load structured run state for partial modes. The JSON sidecar is the source
 * of truth; returns null if absent (caller may fall back to legacy LLM parse
 * of the markdown report).
 */
export async function loadMinedState(targetDir) {
  try {
    const raw = await fs.readFile(path.join(path.resolve(targetDir), STATE_FILE), "utf8");
    return JSON.parse(raw);
  } catch (err) {
    return null;
  }
}
